#Ejercicios Numpy

Ejercicio N5

In [19]:
#Dado el vector x = [2, 3, 4], elévalo al cuadrado y al cubo utilizando únicamente 
#operadores de NumPy. 

import numpy as np
import pandas as pd

x=np.array([2,3,4])

cuad=x**2
cubo=x**3


print(x)
print(cuad)
print(cubo)

[2 3 4]
[ 4  9 16]
[ 8 27 64]


Ejercicio N6

In [ ]:
#Crea una matriz de 3 X 3 con valores aleatorios.
#Multiplica toda la matriz por 0.5 y

import numpy as np

a=np.random.rand(3,3)
b=a*0.5
print(b)

Ejercicio N7

In [8]:
#Dada la siguiente matriz: 
#matriz = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]]) 
# Extrae el número 50. 
# Extrae toda la tercera fila. 
# Extrae solo la primera columna. 

matriz = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(matriz)
print(matriz[1,1])
print(matriz[2,:])
print(matriz[:,0])



[[10 20 30]
 [40 50 60]
 [70 80 90]]
50
[70 80 90]
[10 40 70]


Ejercicio N8

In [11]:
#Rebanado de Sub-matrices: De la matriz anterior, obtén una sub-matriz de 2 X 2 
#que contenga los valores [[20, 30], [50, 60]].


matriz = np.array([[10,20,30],[40,50,60],[70,80,90]])
a=matriz[0:2,0:2]
print(a)


[[10 20]
 [40 50]]


Ejercicio N9

In [12]:
#El Producto Matricial: Crea una matriz A de 2 X 3 y una matriz B de 3 X 2. Realiza el producto matricial (@) y explica por qué el 
#resultado es una matriz de 2 X 2. 

A=np.array([[1,2,3],[4,5,6]])
B=np.array([[1,2],[3,4],[5,6]])

print(A@B)


[[22 28]
 [49 64]]


Ejericicio N10


In [13]:
#10. La Transpuesta: Crea una matriz de $4 \times 2$ con valores del 1 al 8. Aplica la función .T (transpuesta) y
#observa cómo cambian las dimensiones de la matriz.

A=np.array([[1,2],[3,4],[5,6],[7,8]])
print("Matriz A= \n",A)
print("Matriz A transpuesta= \n",A.T)
print("Dimensiones de la matriz A= ",A.shape)
print("Dimensiones de la matriz A transpuesta= ",A.T.shape)



Matriz A= 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Matriz A transpuesta= 
 [[1 3 5 7]
 [2 4 6 8]]
Dimensiones de la matriz A=  (4, 2)
Dimensiones de la matriz A transpuesta=  (2, 4)


#Bonus

In [21]:
diccionario = [
{"genero":"Bachata", "cancion":"La bilirrubina","artista":"Juan Luis Guerra","reproduccion":"32165321"},
{"genero":"Bachata", "cancion":"La vida es un carnaval","artista":"Celia Cruz","reproduccion":"222222"},
{"genero":"Reggaeton","cancion":"Gasolina","artista":"Daddy Yankee","reproduccion":"321116512"},
{"genero":"Pop","cancion":"Shape of you","artista":"Daddy Yankee","reproduccion":"3212336512"},
{"genero":"Rock","cancion":"Bohemian Rhapsody","artista":"Queen","reproduccion":"4123216512"},
{"genero":"Electronica","cancion":"Strobe","artista":"Deadmau5","reproduccion":"321556512"},
{"genero":"Jazz","cancion":"So What","artista":"Queen","reproduccion":"321512"},
{"genero":"pop","cancion":"The Thrill Is Gone","artista":"B.B. King","reproduccion":"32165112122"}

]

datos= pd.DataFrame(diccionario)
display(datos)
datos.shape

,genero,cancion,artista,reproduccion
0,Bachata,La bilirrubina,Juan Luis Guerra,32165321
1,Bachata,La vida es un carnaval,Celia Cruz,222222
2,Reggaeton,Gasolina,Daddy Yankee,321116512
3,Pop,Shape of you,Daddy Yankee,3212336512
4,Rock,Bohemian Rhapsody,Queen,4123216512
5,Electronica,Strobe,Deadmau5,321556512
6,Jazz,So What,Queen,321512
7,pop,The Thrill Is Gone,B.B. King,32165112122


(8, 4)

In [ ]:
#Sumar las reproducciones
datos["reproduccion"]=datos["reproduccion"].astype(int) #transforma columna reproduccion a enteros
total_reproducciones=datos["reproduccion"].sum()
print("Total de reproducciones: ",total_reproducciones)

Total de reproducciones:  40176047225


In [23]:
#Mostrar todo lo asociado a bachata

Bachata=datos[datos["genero"]=="Bachata"]
display(Bachata)

,genero,cancion,artista,reproduccion
0,Bachata,La bilirrubina,Juan Luis Guerra,32165321
1,Bachata,La vida es un carnaval,Celia Cruz,222222
